### PR TITLE
Added WebXR Platform

### PR DESCRIPTION
**Pull request by StephenHodgson**
# XRTK - Mixed Reality Toolkit Pull Request

## Overview

Adds [WebXR](https://github.com/XRTK/WebXR) platform support.

### CODE REVIEW

**Comment by SimonDarksideJ** [comment]
This seems good to merge @StephenHodgson to just add the platform?

**Comment by StephenHodgson** [comment]
Lots of work to be done here still. It's far from ready. I'll update the docs as we get closer to the finish.

**Comment by StephenHodgson** [comment]
Gonna reopen this later

**Pull request closed without merging**
