### PR TITLE
Updated Spatial Awareness Parent Object Transform to fix teleporting

### PR DESCRIPTION
**Pull request by StephenHodgson**
# XRTK - Mixed Reality Toolkit Change Request

## Overview

Parented the SpatialAwarenessParent under the playspace to ensure that the spatial mesh stays in the same place when teleporting

## Target of the change:

Is this enhancement for:

- Core (core framework, interfaces and definitions)

## Changes:

- Moved the Spatial Awareness system's root GameObject reference under the Playspace.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
I've tested this on Magic Leap but not HoloLens yet.

**Comment by StephenHodgson** [comment]
Please don't merge until tested on HoloLens

**Comment by FejZa** [comment]
Testing on HoloLens in a minute

**Comment by FejZa** [comment]
@StephenHodgson tested on HoloLens, works as expected.

**Pull request merged**
