### PR TITLE
Configuration data structure refactor

### PR DESCRIPTION
**Pull request by StephenHodgson**
# XRTK - Mixed Reality Toolkit Change Request

## Overview

A pre-step to consolidating the editor inspector codes for drawing/displaying this list in the editor.

## Target of the change:

Is this enhancement for:

- Core (core framework, interfaces and definitions)

## Changes:

- Renamed the serialized backing fields so we can consolidate all the configuration structs into a single type

## Breaking Changes:

- [Renamed `BaseMixedRealityProfile.IsCustomProfile` to `IsEditable`](https://github.com/XRTK/XRTK-Core/compare/feature/configuration-interfaces...dev/configuration-refactor?expand=1#diff-98957a7bfc4a9966e6bcd07f1d8cbeadR19)
- Removed all the existing configuration data structures and consolidated them into one.
- All of the profiles have been reserialized

### CODE REVIEW

**Comment by StephenHodgson** [comment]
Oh wait, this is still in progress. I need to update the inspectors still.

**Comment by SimonDarksideJ** [comment]
Is this yet ready or is it pending the other PR?

**Comment by StephenHodgson** [comment]
Just need to finish up fixing the inspectors

**Comment by StephenHodgson** [comment]
Inspectors should be done. Only thing left is getting the dropdown filtering working properly again but we can do that later.

**Comment by SimonDarksideJ** [comment]
Not critical since this is due to be refactored, but Input Action Rules config has stopped working, the dropdowns don't work, not sure if it's related to this change

**Pull request merged**
