### PR TITLE
Input Simulation Port: Camera

### PR DESCRIPTION
**Pull request by FejZa**
# XRTK - Mixed Reality Toolkit Change Request

## Overview

This PR builds on top of #226 and adds camera input simulation. The user can navigate the scene using the keyboard and simulate head motion. Please also consider the related PR in SDK https://github.com/XRTK/SDK/pull/47.

## Target of the change:

Is this enhancement for:

- Core (core framework, interfaces and definitions)

## Changes:

- Define inspector and profile for camera input simulation
- Define camera input simulation data provider

### CODE REVIEW

**Comment by StephenHodgson** [comment]
I'm not sure simulation should be used in conjunction with keyboard.

It should be a default input method for platforms that support keyboard input.

**Comment by FejZa** [comment]
I am not sure I understand. How are you going to move / simulate without a keyboard?

**Comment by StephenHodgson** [comment]
There's going to be a need for a switch to disable typical input and switching to the simulated.

This probably just needs more discussion more than anything,

**Comment by FejZa** [comment]
So you mean there needs to be a mechanism e.g. to detect if a headset is connected and providing input then disable the camera simulation?

**Comment by FejZa** [comment]
Which makes me aware of an issue I need to fix. All the simulation must only run when in Editor. Forgot about that.

**Comment by SimonDarksideJ** [comment]
For the editor, input should support Keyboard / Mouse / Gamepad.   (Possibly leap motion for hands, but that is another PR)
Other than that, it isn't relevant for the editor environment.

Headsets are definitely not included, as that would use it's own native input and simulation would not be required

**Pull request closed without merging**
