### PR TITLE
Consolidate and clean up editor assembly

### PR DESCRIPTION
**Pull request by FejZa**
# XRTK - Mixed Reality Toolkit Pull Request

## Overview

This is a housekeeping PR. It removes any editor only assemblies found in the `Runtime/` path of the core module. Any editor specifics are now properly located in the `Editor/` path / assembly of the core module.

This was a necessary step to set a proper foundation while we still can and align the package layout with the new standard.

## Submodule Changes

All submodules had to be updated to adjust namespaces.

- [Pipelines](https://github.com/XRTK/AzurePipelines/pull/2)
- [SteamVR](https://github.com/XRTK/SteamVR/pull/20)
- [Nreal](https://github.com/XRTK/Nreal/pull/13)
- [Lenovo](https://github.com/XRTK/Lenovo/pull/9)
- [Etee](https://github.com/XRTK/Etee/pull/7)
- [ARCore](https://github.com/XRTK/ARCore/pull/9)
- [SDK](https://github.com/XRTK/SDK/pull/220)
- [Lumin](https://github.com/XRTK/Lumin/pull/96)
- [Oculus](https://github.com/XRTK/Oculus/pull/102)
- [Ultraleap](https://github.com/XRTK/Ultraleap/pull/20)
- [WMR](https://github.com/XRTK/WindowsMixedReality/pull/115)
- [WebXR](https://github.com/XRTK/WebXR/pull/8)

### CODE REVIEW

**Comment by FejZa** [comment]
Please hold of refviewing until I create all the submodule PRs and I also need to update a build script for this to pass.

**Comment by FejZa** [comment]
All right. Everything is ready. We need the pipelines change in first so the Unity builds can complete.

**Review by SimonDarksideJ — APPROVED** [review]

**Review by StephenHodgson — APPROVED** [review]

**Comment by SimonDarksideJ** [comment]
It might also be a good idea to put all the other Editor logic under the same pattern, using 

```
XRTK.Editor.Utilities
XRTK.Editor.SDK
XRTK.Editor.Lumin
```

Instead of all the separate XRTK.XXX.Editor namespaces everywhre?

Thoughts @StephenHodgson  / @FejZa 

Wouldn't normally propose, but while we are doing this namespace reshuffle, it kinda makes sense

**Comment by FejZa** [comment]
So the pattern is <root_namespace>.Editor everywhere now.

**Comment by SimonDarksideJ** [comment]
That's my suggestion. As with the updates currently posted, we still have this inconsistency

image

**Comment by FejZa** [comment]
> That's my suggestion. As with the updates currently posted, we still have this inconsistency
> 
> image
> 

Sorry still don't see what you mean? Can you make an example?

**Comment by SimonDarksideJ** [comment]
You changed `XRTK.Utilities.Editor` to `XRTK.Editor.Utilities`

Yet right below it you still have `XRTK.Lenovo.Editor`

Simples :D

**Pull request merged**
