### PR TITLE
Fix auto scene switcher

### PR DESCRIPTION
**Pull request by FejZa**
# XRTK - Mixed Reality Toolkit Pull Request

## Overview

This PR fixes the `AutoSceneSwitcher` showing up when the toolkit is actually already configured in the scene(s).
Also this fixes the `AutoSceneSwitcher` forcing the XRTK base scene to be the active scene. This breaks multi-scene editing behaviour expected from the editor. As only the active scene's lightmaps will be used and people might want another scene to be the active scene in editor. The XRTK does not require the base scene to be the active scene, it just needs to be loaded.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
This is the intended behavior

**Comment by StephenHodgson** [comment]
You should be able to open and edit multiple scenes at once in the editor

**Comment by FejZa** [comment]
What is intended behaviour?

**Comment by FejZa** [comment]
I can open multiple scened and edit them yes, that is not the issue here.

**Comment by SimonDarksideJ** [comment]
I've hit this a few time before which has led me not to use the base scene for these very issues.  Seeing as this fix resolves them, I would welcome it.

**Review by SimonDarksideJ — DISMISSED** [review]

**Comment by StephenHodgson** [comment]
This passed already and I cancelled it bc it will loop forever

**Comment by FejZa** [comment]
I see. I am trying to understand what's wrong with the docs build.

**Comment by StephenHodgson** [comment]
@FejZa could you cherry pick the changes from this PR and open a new one so the doc changes are left behind?

**Comment by FejZa** [comment]
WTH happened here. This PR was a single file changed and no triple slash docs changed at all. How come I have 169 changed files now.

**Comment by StephenHodgson** [comment]
The docs build step. I removed that step now.

**Comment by FejZa** [comment]
Closed in favor of https://github.com/XRTK/XRTK-Core/pull/754

**Pull request closed without merging**
