### PR TITLE
Included platform prefabs in the Symbolic links for dev branch

### PR DESCRIPTION
**Pull request by SimonDarksideJ**
# XRTK - Mixed Reality Toolkit Pull Request

## Overview

Included platform prefabs in the Symbolic links for dev branch

## Changes

Symbolic links updated to include new package hidden folders

## Related changes

- https://github.com/XRTK/Oculus/pull/95
- https://github.com/XRTK/WindowsMixedReality/pull/108

### CODE REVIEW

**Review by StephenHodgson — CHANGES_REQUESTED** [review]
There shouldn't be prefabs in the platform packages

**Comment by SimonDarksideJ** [comment]
There should not be dependencies between the Platforms and another package, e.g. the SDK.  This breaks platforms.
We can work on a better solution for 0.3

**Comment by StephenHodgson** [comment]
I'd much rather see a dependency on the SDK then having to manage duplicate assets across all the platforms

**Comment by SimonDarksideJ** [comment]
If you can resolve #706 in short order, we can reevaluate the way forward. Else we will need to accept this approach in the short term to lead to a future workable arrangement

**Pull request closed without merging**
