### PR TITLE
Update XRTK.Core to 0.2.0

### PR DESCRIPTION
**Pull request by StephenHodgson**
Bumped the version to 0.2.0 to celebrate the native oculus release

Issues that need resolving prior to this merge:

- [ ] #247 
- [ ] #232 
- [ ] #229 
- [ ] #209 
- [ ] #189 
- [ ] #159 
- [ ] #81 
- [ ] #45 
- [ ] #36 ?

### CODE REVIEW

**Comment by SimonDarksideJ** [comment]
I'm ok with bumping dev to 0.2.0 for the pending next release.  But we should hold off merging this until we are sure there are no core changes needed for any final 0.2.0 inclusions that need a new build in the dependant packages

**Comment by StephenHodgson** [comment]
I think it's fine to bump the version but keep the checklist for our release.

**Comment by StephenHodgson** [comment]
We really need the submodule changes asap

**Comment by StephenHodgson** [comment]
We decided to just bump to 0.1.14

**Pull request closed without merging**
