### PR TITLE
Services that utilize uwp capabilities, now properly set them

### PR DESCRIPTION
**Pull request by StephenHodgson**
Ensures that services that use a uwp component are setting them when they're constructor is called in the editor, which then updates the player settings.

When the Mixed Reality Toolkit instance is created all services get their constructors called, even at edit time.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@Alexees I wouldn't mind your review on this, if you have time.

**Comment by Alexees** [comment]
This seem to work, two thoughts though:
- Neither disabling the Spatial Awareness System in the Toolkit configuration profile nor removing it from there removes the capability again.
- This would lead to another fancyness consideration. If there was another service that needs this capability we would need to count them to toggle them off if not one of the services using the capability is active anymore.

**Comment by StephenHodgson** [comment]
> Neither disabling the Spatial Awareness System in the Toolkit configuration profile nor removing the spatial mesh observer from there removes its capability again.

I'm not sure it matters if the capability needs to be removed if it's removed. I don't mind this being a manual task. No harm comes from keeping it unless it's a restricted capability.

> This would lead to another fancyness consideration

The current implementation or the idea you have? I was just going to force them to true, no record keeping there.

**Comment by Alexees** [comment]
just the idea i had. if keeping them true if fine don't bother :)

**Comment by Jarodshow** [comment]
Thanks!

**Pull request merged**
