### PR TITLE
Add simple camera controls when running in editor to camera system

### PR DESCRIPTION
**Pull request by FejZa**
# XRTK - Mixed Reality Toolkit Change Request

## Overview

This PR will add simple camera control options to the camera system profile, when running in editor. It allows to move the camera rig in the scene using keyboard and mouse. Direct port of MRTK's camera controls for the Unity Editor with minor adjustments.

## Target of the change:

Is this enhancement for:

- Core

## Changes:

Brief list of the targeted features that are being changed.

- Adds camera editor controls configuration options to the camera system profile.

## Breaking Changes:

- None

### CODE REVIEW

**Comment by FejZa** [comment]
editor_camera_controls_profile

**Comment by FejZa** [comment]
https://github.com/XRTK/SDK/pull/72

**Comment by FejZa** [comment]
I do understand. But honestly, we've been overcomplicating / overengineering this thing for a while now. Here's my thoughts:

- I did the change like this since it does not affect anything else and is basically a no-brainer
- I added it so that once we have something superior in place, removing the whole thing is a matter of 2 minutes
- It's simple and effective and adds the ability to move in the scene. This is a feature people would expect right from the start. People have been asking for it when the first public MRTK alpha launched and I am certain it's turn off to not have it when starting work with XRTK

Happy to make changes but I really do think we should consider having this simplistic solution in place while we work out a "proper" solution.

**Comment by StephenHodgson** [comment]
I'm fine with adding the camera controls, as long as they're done using the `InputActions`

**Comment by StephenHodgson** [comment]
`Editor controls == standlone input`

**Comment by FejZa** [comment]
Alright, I'll review once more. Focusing on hand tracking for now. This can now be worked on separated from the hand tracking, since I rewrote the whole thing and there is no simulation system whatsoever in place anymore. Separate things now.

**Comment by StephenHodgson** [comment]
@FejZa can we close this until we have proper support using Input Actions?

**Comment by FejZa** [comment]
@StephenHodgson we can close this PR. But please keep the branch.

**Pull request closed without merging**
