### PR TITLE
EditorBuildSettings.scenes fixes

### PR DESCRIPTION
**Pull request by SimonDarksideJ**
# XRTK - Mixed Reality Toolkit Change Request

## Overview

If accessed when not initialized (I.E. in a brand new Unity project) Unity will crash.
To avoid this, the necessary checks have been added to ensure it's ready before use to avoid this Unity bug.

## Target of the change:

Is this enhancement for:

- Core (core framework, interfaces and definitions)

## Changes:

Brief list of the targeted features that are being changed.

- Fixes: Adds null checking and Length checking of the EditorBuildSettings.scene array

### CODE REVIEW

**Comment by StephenHodgson** [comment]
Try running the build locally.

**Comment by SimonDarksideJ** [comment]
Can't replicate but I've added some extra checking around the lines it's reporting an issue.

**Comment by StephenHodgson** [comment]
Hmm. I wonder why the build is still failing?

**Comment by SimonDarksideJ** [comment]
OK, I've reverted the additional changes beyond the original bug (the extra changes I made for protection).  If this still fails I'll redo the PR from a fresh branch

**Comment by SimonDarksideJ** [comment]
Ok, so that build worked.  Will just have to merge this one fix and then re-test.
No idea why the other build failed which is concerning.

**Pull request merged**
