### PR TITLE
Added json files to the list of UnityFileExtensions

### PR DESCRIPTION
**Pull request by StephenHodgson**
# XRTK - Mixed Reality Toolkit Pull Request

## Changes

- Fixes: #689 
- Fixes: https://github.com/XRTK/SDK/issues/201

### CODE REVIEW

**Comment by SimonDarksideJ** [comment]
Thanks @StephenHodgson , this will be very useful for the Steam platform, so long as it is able to return the path to the json files.

**Review by FejZa — APPROVED** [review]

**Pull request merged**
