### PR TITLE
Release 0.2.0

### PR DESCRIPTION
**Pull request by StephenHodgson**
# 🚧 TODO 🚧 

- [x] #524 Service Locator Refactor
- [x] #517 Camera System Refactor
- [x] #504 Spatial Awareness Refactor
- [x] #508 Controller Mapping Refactor
- [x] #549 Cleanup packages to make sure everything lives in the correct place
- [x] #550 CI/CD Pipeline Upgrade
- [x] #554 Add platform profile installer to ensure new platforms get their data providers registered
- [x] #558 Improved UPM package installation
- [x] #559 Fix canvas utility issue
- [x] #561 Fix controller popout NRE
- [x] #562 update package installer to regenerate asset guid references
- [x] #563 update sdk package to use hidden `Prefabs~` folder
- [x] #570 Service Wizard
- [x] #560 Controller near interactions
- [x] #590 Fix camera rig setup on configure
- [x] #591 Fix blank runtime platforms on installed platform configurations
- [x] #552 Hand input and gesture actions
- [X] https://github.com/XRTK/SteamVR/issues/11 Fix OpenVR controller offset
- [x] https://github.com/XRTK/SDK/issues/203 Build errors when validating project assets
- [x] #675 Fix platform configurations
- [x] https://github.com/XRTK/SDK/issues/201 Missing asset files after SDK import via UPM
- [x] #649 Fix NRE when creating new `IMixedRealityCameraRig`
- [x] Update project to latest 2019.4 LTS release
- [x] #700 Symlink step "Updating Submodules" shows up for too long
- [x] #702 Prompt user to install SDK if no configurations found
- [x] #504 Fix teleporting
- [x] https://github.com/XRTK/XRTK-Core/pull/694 Update Spatial Awareness System
- [x] https://github.com/XRTK/WindowsMixedReality/issues/87 Fix NRE when no camera data provider is setup for the platform
- [ ] ~#603 Go fully native~

## :shipit: Release Tasks
- [x] #580 Create a preview upm package every time development branch gets updated when there is an active pull request to the master branch
- [x] #584 Update getting started documentation
- [x] #670 Documents Checklist
- [x] Follow [Test Plans](https://github.com/XRTK/XRTK-Core/blob/development/articles/testplans/TP_Overview.md)
- [x] Test Core installation only
- [x] Test Core & SDK Installation only
- [x] Test Core & all packages

### CODE REVIEW

**Comment by StephenHodgson** [comment]
azp/ run

**Comment by StephenHodgson** [comment]
I think we're almost ready!

**Comment by StephenHodgson** [comment]
@SimonDarksideJ @FejZa is there anything pending in the Core that we need to wait for?

**Comment by SimonDarksideJ** [comment]
Let's go through a last round of testing to be sure.

**Review by SimonDarksideJ — APPROVED** [review]

**Pull request merged**
