### PR TITLE
updated editor to 2019.4.29f1

### PR DESCRIPTION
**Pull request by StephenHodgson**
# XRTK - Mixed Reality Toolkit Pull Request

## Overview
- updated editor to 2019.4.29f1
- replaces package submodues with relative manifest registration

### CODE REVIEW

**Comment by FejZa** [comment]
What is relative manifest registration? Gotta check it out.

**Comment by StephenHodgson** [comment]
Basically we don't need to define the submodules as symbolic links, it'll help in the long term with project management

**Review by FejZa — APPROVED** [review]
I like

**Pull request merged**
