### PR TITLE
Fix controller popup nre's for new controller

### PR DESCRIPTION
**Pull request by SimonDarksideJ**
# XRTK - Mixed Reality Toolkit Change Request

## Overview

Resolved a new issue for when a new controller is defined but not yet initialised

Requires #461

### CODE REVIEW

**Comment by SimonDarksideJ** [comment]
Built on top of #461, which needs to be merged first.

**Comment by SimonDarksideJ** [comment]
I just need to sync the branch as they weren't part of this change

**Comment by SimonDarksideJ** [comment]
#Nudge @StephenHodgson

**Comment by StephenHodgson** [comment]
Sorry, I'll check this asap

**Pull request merged**
