### PR TITLE
Cross platform Controller validation to resolve #247

### LINKED ISSUE #247: Controller management required for situations where multiple data providers can exist on a single platform
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

With Windows Mixed Reality, OpenVR was for standalone and WMR was for UWP, there was a clear separation

Now with the addition of Oculus, we have situations where multiple data providers can compete for the controllers to manage, resulting in multiple data providers capturing and rendering the detected controllers.

Seems we need a higher level controller management framework to ensure that once a controller is activated and registered, it is ignored by any other provider.

## To Reproduce

1. Enable Joystick / OpenVR & Oculus on Windows Standalone (default behaviour)
2. Run the project with Oculus VR as the primary VR target
3. Observe that multiple controllers exist in the scene, some tracked and some not

## Expected behavior

Once a controller is active, it should be ignored by other data providers

## Actual behavior

Free for all, everyone registers and renders

## Your Setup (please complete the following information)

- Unity Version 2019.1.10
- XRTK Version 0.1.13

## Target Platform (please complete the following information)

- Windows Standalone

### PR DESCRIPTION
**Pull request by SimonDarksideJ**
# XRTK - Mixed Reality Toolkit Change Request

## Overview

Updating Controller detection logic to use Input System Detected controllers for platforms that can have multiple systems running on them (aka Windows Standalone)

## Target of the change:

Is this enhancement for:

- Core (core framework, interfaces and definitions)
- Platform (new or updated platform)

## Changes:

* Controller Type added to IMixedRealityController
* Added new TryGet method to InputSystem (and interface) to Query detected by Type and Hand
* All current controller constructors updated to include type
* All current controller instantiation updated to include type
* Updated Logic for OpenVR to check the input system for detected controllers
* Updated Logic for Oculus to check the input system for detected controllers

WMR / Lumin unaffected, as they can only ever have one set of detected controllers

## Breaking Changes:

As the changes are limited to the internal controller management, there should be no breaks
Changes to Input System are additive, so should not cause breaks

## TODO

- [ ] Resolve issue with the Generic Joystick control, it does not recognise the controller at all and still attempts to load.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@SimonDarksideJ any update to this?

**Comment by SimonDarksideJ** [comment]
Still working on it, got hit by a few issues and then sidetracked by quest.
May close and restart once your InputActions PR is done

**Comment by StephenHodgson** [comment]
Np just wanted to check in.

**Comment by SimonDarksideJ** [comment]
Closing for now and we re-evaluate post the InputActions update

**Pull request closed without merging**
