### PR TITLE
Bump Core version

### PR DESCRIPTION
**Pull request by FejZa**
# XRTK - Mixed Reality Toolkit Pull Request

## Overview

Bumps the core version up to 0.2.1 due to recent breaking changes.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
We may want to bump the versions in the submodules as well since they have that breaking change

**Review by StephenHodgson — APPROVED** [review]

**Comment by StephenHodgson** [comment]
This wasn't done running in azure was it?

**Comment by StephenHodgson** [comment]
How did it get merged?

**Comment by StephenHodgson** [comment]
Oh don't mind me. I'm confused lol

**Comment by FejZa** [comment]
@StephenHodgson it never ran. Just as confused as you. When I created the PR I got a message from GitHub saying something along the lines "skipped checks because branch filter (or was it path filter?) did not match".

I think a PR with only a change in the package.json doesn't seem to qualify for a build.

**Comment by StephenHodgson** [comment]
that is correct. No worries, I was confused about which PR this was. pay no mind to my prev comments lol

**Pull request merged**
