### PR TITLE
Spatial Mesh Observer offset port

### PR DESCRIPTION
**Pull request by StephenHodgson**
# XRTK - Mixed Reality Toolkit Change Request

## Overview

Added spatial anchor offset logic for when users change the playspace location in relation to the visualized spatial mesh. (i.e. Teleportation with spatial meshes)

## Target of the change:

Is this enhancement for:

- Core (core framework, interfaces and definitions)
- Platform (new or updated platform)
- Component ported from another framework

## Changes:

Added an `Anchor` property to the `SpatialMeshObject` and made sure to set the `WorldAnchor` to it for WMR. Not sure what the equivalent is for Magic Leap.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
I don't have a HoloLens to test this change on, and don't want it merged until we've really tested this well.

I have some concerns about this change:

1. After a player has teleported will new spatial meshes be placed in the correct position?

**Comment by SimonDarksideJ** [comment]
My HoloLens hasn't been returned yet. I shall chase for an update.
Perhaps a call out to the XRTK contrib group for specific HL testing?

**Comment by FejZa** [comment]
I can test it if we are Talking About HoloLens 1 here.

**Comment by StephenHodgson** [comment]
@FejZa please do 😄

**Comment by FejZa** [comment]
@StephenHodgson can you explain a bit more what to test? Not sure how I am supposed to teleport with a HoloLens. Do I need to write some custom logic to move the camera to a different location?

**Comment by StephenHodgson** [comment]
Good question. I used to have a HL teleport script around. I'll have to dig it up and see if I can find it.

Really the only thing to test is to make sure that the spatial mesh is correctly placed after teleporting the user to a new location.

**Comment by StephenHodgson** [comment]
Gotcha, I'll take a look at this at some point.

**Comment by SimonDarksideJ** [comment]
Nudge @StephenHodgson , any update?

**Pull request closed without merging**
