### PR TITLE
updated sdk and wmr package layout and profile location

### PR DESCRIPTION
**Pull request by StephenHodgson**
# XRTK - Mixed Reality Toolkit Change Request

## Overview

Reorganized each of the packages to conform to the [upm standard package layout](https://docs.unity3d.com/Manual/cus-layout.html).

This PR is not meant to address moving the profiles to their respective packages yet.

No logical code changes made, only moved folders and updated editor namespaces.

## Submodule Changes

- [x] [SDK](https://github.com/XRTK/SDK/pull/163)
- [x] [WMR](https://github.com/XRTK/WindowsMixedReality/pull/73)
- [x] [Lumin](https://github.com/XRTK/Lumin/pull/69)
- [x] [Oculus](https://github.com/XRTK/Oculus/pull/64)

### CODE REVIEW

**Comment by SimonDarksideJ** [comment]
One issue I have with their "standard" is it has no motion of a plugins folder, which is needed for any package that needs to ship platform dll's, like oculus

**Comment by StephenHodgson** [comment]
Pretty sure it just goes `Runtime/Plugins`

**Comment by StephenHodgson** [comment]
I'd like to either do this asap or last. Up to you guys. I guess it depends on how many PRs we wanna deal with, but it should be a straight forward file move. No real changes except for the `Inspectors` -> `Editor` namespace change.

**Comment by FejZa** [comment]
I think the only thing currently being worked on by me is the feature/hands-input branch which should have all current development upstream changes, since last weekend I haven't been working on it. So I am fine with getting this in now and then continuing work.

**Pull request merged**
