### PR TITLE
clickable services without having to open foldout

### PR DESCRIPTION
**Pull request by StephenHodgson**
# XRTK - Mixed Reality Toolkit Pull Request

## Overview
Added the ability to click on services to open their configurations with less clicks. should work automatically for all services and data providers.
D3FdIz6vLi

## Changes

- fixes: #799 
- fixed an invalid cast exception when navigating back to the input system profile from a controller data provider profile
- ensured that the foldout stays open when a profile is expected in the service configuration
- fixed an issue in the input system profile where the "Gaze Cursor Prefab" label would disappear when the `IMixedRealityInputDataProvider` property was closed.

## Submodule Changes

- https://github.com/XRTK/Examples/pull/41
- https://github.com/XRTK/Lumin/pull/114
- https://github.com/XRTK/WindowsMixedReality/pull/142

### CODE REVIEW

**Review by FejZa — APPROVED** [review]
Looks good. I'd like Simon to check as well. Not sure how this happened but looks to me like two people invested time in addressing the same thing and we ended up with two solutions.

**Review by SimonDarksideJ — APPROVED** [review]

**Comment by SimonDarksideJ** [comment]
It is frustrating that several paths were developed for the same solution. We just need to get better/more serious about feeding back into feature request tasks to avoid duplication. (and not just dismiss because we aren't interested)

We need to evolve requirements about Requests with any relevant views with Constructive feedback (solutions not dismissals)

**Comment by StephenHodgson** [comment]
Understandable. From a purely objective criticism, I was worried the changes were too broad without adequately addressing all the services and data providers. The changes here are targeted and doesn't require us to add additional classes or icon assets.

**Pull request merged**
