### PR TITLE
Updated collider extension

### PR DESCRIPTION
**Pull request by StephenHodgson**
# XRTK - Mixed Reality Toolkit Change Request

## Overview

I realized that it'd be better to let any collider be able to utilize this extension.

## Target of the change:

Is this enhancement for:

- Extensions

## Changes:

Makes any collider be able to utilize the `GetCornerPositionsWorldSpace` extension to calculate the bounds corner positions.

### CODE REVIEW

**Comment by SimonDarksideJ** [comment]
Is this not a breaking change?  requiring an SDK update

**Comment by StephenHodgson** [comment]
It's not a breaking change cause it doesn't require any changes to existing code

**Comment by SimonDarksideJ** [comment]
Approved but build failed

**Comment by StephenHodgson** [comment]
I'll take a look see

**Pull request merged**
